# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Yannis Spiliopoulos'
tagline:          ''
description:      ''
url:              http://spiliopoulos.github.io/

paginate:         1
paginate_path:    /blog/page:num

# Custom vars
version:          0.1
