# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Roxana Geambasu'
tagline:          'Assistant Professor of Computer Science at Columbia University <br/>(first-name@cs.columbia.edu)'
description:      ''
url:              http://roxanageambasu.github.io/

paginate:         1
paginate_path:    /blog/page:num

# Custom vars
version:          0.1
